services:
  web:
    build:
      context: ./adminlte3
      dockerfile: Dockerfile.prod
    command: gunicorn adminlte3.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/adminlte3/web/static
      - media_volume:/home/adminlte3/web/mediafiles
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:15
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/adminlte3/web/static
      - media_volume:/home/adminlte3/web/mediafiles
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
