version: '3.8'

services:
  web:
    build: ./adminlte3
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./adminlte3/:/usr/src/adminlte3/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=adminlte3
      - POSTGRES_PASSWORD=123qwe@@
      - POSTGRES_DB=adminlte3

volumes:
  postgres_data:
